// ignore_for_file: leading_newlines_in_multiline_strings

const String privacyPolicyDetails =
    """The User hereby consents, expresses and agrees that he has read and fully understands the Privacy Policy of 4TechVentures in respect of the Website, The User further consents that the terms and contents of such Privacy Policy are acceptable to him.Any customer grievances can be reported to the Grievance Officer specifically dedicated to address all customer concerns. You may contact the Grievance Officer at 4Techventures@gmail.com""";
const String tAndCPolicyDetails =
    """The Bookario app is an internet based entertainment ticketing portal owned and operated by 4Tech Ventures a company incorporated under the laws of India, with its registered office B-1106 Urban Space, next to the Royal Heritage Mall, Mohammadwadi- 411048.

Through the Website, Bookario shall provide you ("User") entertainment-related information, pricing, availability and reservations for ticket for cinemas, plays, concerts, sports events across cities and rural areas throughout India ("Service"), as more particularly described and defined in the terms of service ("TOS") relating to such Service, This Service may be availed by the User, his family members

This User Agreement ("Agreement") sets out the terms and conditions on which Bookario shall provide the Services to the User through the Website. In addition to this Agreement and depending on the Services opted for by the User, the User shall be required to read and accept the relevant TOS for such Service, which may be updated or modified by Bookario from time to time. Such TOS shall be deemed to be a part of this Agreement and in the event of a conflict between such TOS and this Agreement, the terms of this Agreement shall prevail.

It is clarified that terms and conditions specific to an event in respect of which 4Tech Ventures has facilitated sale of tickets through Bookario (“Event”) shall be published on the event page accessible on the Bookario Platform. 4TechVentures publishes such information as provided by and on behalf of the organizer associated with such Event (“Event Organizer”). In the event of any conflict between the Event-related terms and conditions, and this T&C, User agrees that the Event-related terms and conditions shall prevail and be binding on the User at all times.
""";
const String refundPolicyDetails =
    """In case You have made the payment but failed to receive any email and/or SMS confirmation, then chances are that such a payment has failed. Once we have confirmed a failed order, we process refunds on our own. While we process such refunds within 3-5 days, it may take up to 7-10 working days (and sometimes more) for your financial institution to credit the amount back to your account.Bookario reserves the right to deny refunds for tickets purchased outside of Bookario Platform. Any decisions taken by the event organiser and Bookario management will be final and binding in this regard. If you find that you have been issued fake tickets not authorized by us, then you may be a victim of fraud, for which you may consider filing appropriate police complaints/first information report at the nearest police station having jurisdiction over the area of your residence. We bear no responsibility or liability, under any law or circumstances, for such frauds committed by unauthorized third parties.""";
const String cancellationPolicyDetails =
    """ANY TICKET PURCHASED THROUGH THE BOOKARIO PLATFORM IS MEANT SOLELY AND EXCLUSIVELY FOR PERSONAL USE BY THE PERSON IN WHOSE NAME THE TICKET HAS BEEN ISSUED. TICKETS ARE NOT A TRANSFERABLE PROPERTY AND CANNOT BE RESOLD, TRANSFERRED OR CONVEYED TO ANY PERSON UNLESS PRIOR WRITTEN AND EXPRESS PERMISSION HAS BEEN PROVIDED BY THE EVENT ORGANIZER. ANY PERSON FOUND ABUSING TICKETS FOR PERSONAL GAIN OR FOR COMMERCIAL USE SHALL BE LIABLE TO SUITABLE LEGAL PROCEEDINGS INCLUDING THOSE RELATED TO BLACK MARKETING AND FINANCIAL & CRIMINAL FRAUD.

If 4TechVentures or the Event Organizer finds that You are transferring or selling, or You had in the past transferred or sold, Your tickets, including m-ticket or band, through any mode, including social media platforms, other ticketing platforms, by hand, thereby allowing any other person to access the Event without purchasing the ticket from Bookario Platform, then 4TechVentures or the Event Organizer may initiate suitable legal proceedings.Tickets once sold cannot be exchanged, cancelled, modified, transferred, or refunded, and You shall not make any request for modifications in the ticket, including change in date, time, location, or category unless the Event Organizer has specified so in the Event’s terms and conditions. Please make sure You check the date, time, and location before You book Your tickets. But we’d still advise You to read the terms and conditions for each Event regarding exchange, cancellation, modification, transfer, and refund. If You wish to change or modify your ticket details, the same shall be entirely at the discretion of the Event Organizer.If an Event is cancelled or postponed and the Event Organisers of such Event agree on issuing a refund for the tickets, it shall be the Event Organiser's sole responsibility to contact You and process the refund and 4TechVentures shall have no liability in this regard. However, the convenience fee charged by Bookario is non-refundable. If the Event Organizer informs to process the refunds on their behalf, your refunds may reflect in Your account within seven (07) to ten (10) working days from the date of receiving the refund request.

Pune Law Courts alone shall have the sole jurisdiction to enter in and settle any disputes.""";
